os: linux
dist: xenial
language: python
python: 3.6
install:
  - pip install -r requirements.txt
script:
  - mkdir build
  - cp parameter.json build/
  - python empirical_compare.py
  - python plot_art/plot_art.py

